### ISSUE TITLE
[Terminal socket] Uncaught error pops up at startup and socket fails to establish when using a network proxy

### ISSUE THREAD

**Issue by davidnegreira** [GitSquared/edex-ui#222]
When in start the app i have this error:

error     [object Event]: Uncaught [object Event]
debug     at /edex-ui/src/classes/terminal.class.js 111:43

My system is: 
Terminal: konsole 
OS: KDE neon

**Comment by unclevan** [comment]
same problem for me

**Comment by GitSquared** [comment]
Does this happen immediately on startup?

**Comment by davidnegreira** [comment]
yes on startup, I paste all log from npm start:

▶  start     Starting eDEX-UI v1.0.0
ℹ  info      With Node 8.9.3 and Electron 2.0.13
ℹ  info      Renderer is Chrome 61.0.3163.100
▶  Startup   Initialized timer...
ℹ  info      Base config dir is .config/eDEX-UI
☐  pending   Loading settings file...
✔  success   Settings loaded!
☐  pending   Creating new terminal process on port 3000
✔  success   Terminal back-end initialized!
ℹ  info      Creating window...
…  watching  Waiting for frontend connection...
✖  error     [object Event]: Uncaught [object Event]
⬤  debug     at src/classes/terminal.class.js 111:43
●  note      UpdateChecker: Could not fetch latest release from GitHub's API.
⬤  debug     Error: Error: connect ETIMEDOUT 192.30.253.116:443

**Comment by GitSquared** [comment]
@davidnegreira @unclevan Do you run anything on local port 3000-3005?
Also does that error make the window crash/freeze or is it just a pop-up you can dismiss?

**Comment by Enoooch** [comment]
I got this problem too, here is my log:

...
✔  success   Terminal back-end initialized!
ℹ  info      Creating window...
2018-11-22 10:53:11.734 Electron[23841:1192108] *** WARNING: Textured window <AtomNSWindow: 0x7fdb3e443f30> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
…  watching  Waiting for frontend connection...
☒  complete  Frontend window is up!
ℹ  info      UpdateChecker: Running latest version.
✖  error     [object Event]: Uncaught [object Event]
⬤  debug     at file:///Users/enoch/Projects/edex-ui/src/classes/terminal.class.js 111:43

1. The textured window warning above, I don't know how to fix it. 
2. And the error happens after window is up.

This is my interface:
![1542856542665](https://user-images.githubusercontent.com/39915133/48879715-f8db2400-ee47-11e8-8175-c74c9215376f.jpg)

3. Can not use terminal and file system.

**Comment by unclevan** [comment]
> I got this problem too, here is my log:
> 
> ...
> ✔ success Terminal back-end initialized!
> ℹ info Creating window...
> 2018-11-22 10:53:11.734 Electron[23841:1192108] *** WARNING: Textured window <AtomNSWindow: 0x7fdb3e443f30> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
> … watching Waiting for frontend connection...
> ☒ complete Frontend window is up!
> ℹ info UpdateChecker: Running latest version.
> ✖ error [object Event]: Uncaught [object Event]
> ⬤ debug at file:///Users/enoch/Projects/edex-ui/src/classes/terminal.class.js 111:43
> 
> 1. The textured window warning above, I don't know how to fix it.
> 2. And the error happens after window is up.
> 
> This is my interface:
> ![1542856542665](https://user-images.githubusercontent.com/39915133/48879715-f8db2400-ee47-11e8-8175-c74c9215376f.jpg)
> 
> 1. Can not use terminal and file system.

![2018-11-22 13 02 05](https://user-images.githubusercontent.com/6104451/48882756-0055f980-ee57-11e8-819a-cb247ef2fa43.png)

**Comment by unclevan** [comment]
![2018-11-22 13 02 05](https://user-images.githubusercontent.com/6104451/48882818-82462280-ee57-11e8-8488-9d4bf7891796.png)

**Comment by GitSquared** [comment]
@Enooch The textured window warning is unrelated and will be fixed when the next electron v3 release is published & eDEX migrates to it.

From the screenshots I can tell that the problem is that the internal websocket that connects eDEX and the actual terminal process fails to establish and drops and error.

Unfortunately the error message isn't really helpful. I'm going to try and make it output something more interesting.

**Comment by GitSquared** [comment]
Could anyone try to run this again and tell me what's the error now?

**Comment by Enoooch** [comment]
The latest version works for me, no error this time, only the warning left, thanks!

**Comment by GitSquared** [comment]
...i didnt change anything. What the hell.

**Comment by Enoooch** [comment]
...That's odd.
I am running this code in dev mode, this is my log now:

ℹ  info      Creating window...
2018-11-22 20:45:00.259 Electron[40481:2300690] *** WARNING: Textured window <AtomNSWindow: 0x7ff5f7c56310> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
…  watching  Waiting for frontend connection...
☒  complete  Frontend window is up!
✔  success   Connected to frontend!
◼  Startup   Timer run for: 12.73s
ℹ  info      Resized TTY to  066 031
ℹ  info      Resized TTY to  103 030
ℹ  info      UpdateChecker: Running latest version.
●  note      LocationGlobe: Error parsing data from ipinfo.now.sh
⬤  debug     Error: TypeError: Cannot read property 'latitude' of undefined

Terminal and filesystem are available now.

**Comment by GitSquared** [comment]
Hoooo. @unclevan do you think your proxy might have been blocking local connections?

**Comment by davidnegreira** [comment]
> When I shut down the network proxy, everything was fine...

same here, when I do:
unset http_proxy
unset https_proxy

everything works fine

**Comment by GitSquared** [comment]
Nice. Now I know what's wrong. Will fix asap.

**Comment by Fedrius** [comment]
> When I shut down the network proxy, everything was fine...

I just had this same issue. It was because I had my rails dev server running on port 3000. Once I stopped the server, EDEX-UI worked again.

**Comment by GitSquared** [comment]
@Fedrius About that, you can change the port used by eDEX in the settings. See the wiki.

**Comment by GitSquared** [comment]
I've implemented a fix based on @davidnegreira's comment. On startup, the `http_proxy` and `https_proxy` env variables are disabled.

**Comment by abhiunix** [comment]
Sir, I'm still facing the same issue with the same error message.
I have also checked my port no 3000.
No other services are using this port.

![Screenshot 2019-05-12 at 1 31 03 AM](https://user-images.githubusercontent.com/29152087/57574381-a7563e00-7455-11e9-9308-bb4d13cffe64.png)

**Comment by GitSquared** [comment]
@abhiunix Two things:

- Do you use a network proxy?
- Does changing eDEX's settings to use some other port (e.g `3001`) fixes the issue?
