### ISSUE TITLE
Uncaught SyntaxError when opening files via file browser

### ISSUE THREAD

**Issue by akbiggs** [GitSquared/edex-ui#308]
"Uncaught SyntaxError: Invalid or unexpected token at file:///Applications/eDEX-UI.app/Contents/Resources/app.asar/ui.html 1:56"

Investigating that file to see what it's complaining about exactly.

This is in the 1.1.1 release, OS is Mac OS X High Sierra.

**Comment by GitSquared** [comment]
Without running from source, you won't get much useful info via the error messages i'm afraid, source code is minified for release. I think this might be something i already fixed on the master branch though.

**Comment by GitSquared** [comment]
Releasing new version in the next hours - feel free to reopen if the bug appears again.

**Comment by DeftNerd** [comment]
I was seeing this error too. Upgraded to v1.1.2 and I'm still seeing the error. 

I deleted my .config/eDEX-UI folder and relaunched to regenerate the config folder just in case it was something wrong in a settings file... didn't help, error still happens when I click on a file. 

OS is Ubuntu Bionic 18.04

**Comment by Nightmarlin** [comment]
v1.1.2
This appears to occur on any file opened in the explorer view. It also has some weird behaviour

1. Click item
-> Error occurs
![image](https://user-images.githubusercontent.com/29228454/49370065-05366b00-f6eb-11e8-8bcc-343edfd2138b.png)
2. Click another item
-> Same error occurs, different location in file
![image](https://user-images.githubusercontent.com/29228454/49370114-27c88400-f6eb-11e8-8807-1f27dc63f909.png)
3. Click first item
-> No error occurs
4. Navigate to a different folder and back
5. Click first item
-> Original error occurs
![image](https://user-images.githubusercontent.com/29228454/49370179-5f373080-f6eb-11e8-974e-3c1d0dc246f0.png)

Tested with changes to .config file to no avail

**Comment by GitSquared** [comment]
Successfully reproduced, fix underway.

**Comment by GitSquared** [comment]
(Sorry for the delay :x)
